# Generated by Django 3.2.6 on 2021-09-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='events',
            field=models.ManyToManyField(related_name='orgs', to='orgs.Event'),
        ),
    ]
