# Generated by Django 3.2.6 on 2021-09-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_org_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='user',
            field=models.CharField(default='sample@email.com', max_length=100),
            preserve_default=False,
        ),
    ]
