# Generated by Django 3.2.6 on 2021-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_org_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
