# Generated by Django 3.2.6 on 2022-01-12 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0006_auto_20210919_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=500)),
                ('org_body', models.CharField(choices=[('COA', 'COA'), ('LIONS', 'LIONS'), ('Sanggu', 'Sanggu')], max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('events', models.ManyToManyField(blank=True, related_name='orgs', to='orgs.Event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Org',
        ),
    ]
