# Generated by Django 3.2.6 on 2022-02-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_auto_20220112_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='coverphoto/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_photo1',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_photo2',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_photo3',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_photo4',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
        migrations.CreateModel(
            name='StudentToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('id_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('course', models.CharField(max_length=32)),
                ('date_submitted', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='orgs.event')),
            ],
        ),
    ]
