# Generated by Django 3.2.6 on 2022-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_auto_20220202_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepting_responses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='form_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='is_past_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='old_respondents',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
