# Generated by Django 3.2.6 on 2022-02-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_auto_20220222_2116'),
        ('orgs', '0010_auto_20220223_0956'),
    ]

    operations = [
    ]
