# Generated by Django 3.2.6 on 2022-03-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_merge_0010_auto_20220222_2116_0010_auto_20220223_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttoevent',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studenttoevent',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studenttoevent',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studenttoevent',
            name='year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ('6th Year', '6th Year'), ('7th Year', '7th Year')], max_length=100),
        ),
    ]
