# Generated by Django 3.2.6 on 2022-03-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_auto_20220301_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('id_number', models.IntegerField()),
                ('email', models.EmailField(max_length=200, null=True)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ('6th Year', '6th Year'), ('7th Year', '7th Year')], max_length=100)),
                ('course', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='studenttoevent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studenttoevent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studenttoevent',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='studenttoevent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studenttoevent',
            name='year',
        ),
        migrations.AlterField(
            model_name='studenttoevent',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='orgs.event'),
        ),
        migrations.AddField(
            model_name='studenttoevent',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='orgs.student'),
        ),
    ]
