# Generated by Django 3.2.6 on 2022-03-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0013_auto_20220309_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttoevent',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='orgs.event'),
        ),
        migrations.AlterField(
            model_name='studenttoevent',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='orgs.student'),
        ),
    ]
