# Generated by Django 3.2.6 on 2022-03-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_auto_20220309_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttoevent',
            name='student',
        ),
        migrations.AddField(
            model_name='studenttoevent',
            name='student',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='event', to='orgs.Student'),
        ),
    ]
