# Generated by Django 3.2.6 on 2022-03-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_auto_20220314_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttoevent',
            name='student',
            field=models.ManyToManyField(blank=True, default=None, related_name='event', to='orgs.Student'),
        ),
    ]
