# Generated by Django 3.2.6 on 2022-04-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_alter_studenttoevent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.IntegerField(unique=True),
        ),
    ]
