# Generated by Django 3.2.6 on 2022-04-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_auto_20220401_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
