# Generated by Django 3.2.6 on 2023-07-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_organizationaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationaccount',
            old_name='user',
            new_name='name',
        ),
    ]
