# Generated by Django 3.2.6 on 2023-07-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_auto_20230713_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
        migrations.AlterField(
            model_name='organizationaccount',
            name='organization',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
        ),
    ]
