# Generated by Django 3.2.6 on 2021-08-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20210825_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
