# Generated by Django 3.2.6 on 2021-09-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_alter_org_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='events',
        ),
    ]
