# Generated by Django 3.2.6 on 2021-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_alter_org_org_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='events',
        ),
        migrations.AddField(
            model_name='org',
            name='events',
            field=models.ManyToManyField(to='orgs.Event'),
        ),
    ]
